# Generated by Django 5.2.7 on 2025-10-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre_partido', models.CharField(max_length=200, unique=True, verbose_name='Nombre del partido')),
                ('sigla', models.CharField(max_length=20, verbose_name='Sigla')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del logo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partidos',
                'ordering': ['nombre_partido'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL de foto del candidato')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='core.cargo', verbose_name='Cargo al que postula')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='core.region', verbose_name='Región (solo para Diputados)')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='candidatos.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'db_table': 'candidatos',
            },
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('tipo', models.CharField(choices=[('denuncia', 'Denuncia'), ('proyecto', 'Proyecto'), ('propuesta', 'Propuesta')], max_length=20, verbose_name='Tipo de antecedente')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha', models.DateField(verbose_name='Fecha del antecedente')),
                ('fuente_url', models.URLField(blank=True, null=True, verbose_name='Fuente oficial')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='candidatos.candidato', verbose_name='Candidato')),
            ],
            options={
                'verbose_name': 'Antecedente',
                'verbose_name_plural': 'Antecedentes',
                'db_table': 'antecedentes',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['candidato', 'tipo'], name='antecedente_candida_84e0c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='candidato',
            index=models.Index(fields=['cargo', 'region'], name='candidatos_cargo_i_4b692b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidato',
            index=models.Index(fields=['partido'], name='candidatos_partido_d6b63a_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('nombre', 'apellido_paterno', 'apellido_materno', 'cargo', 'region'), name='unique_candidato_cargo_region'),
        ),
    ]
