# Generated by Django 5.2.7 on 2025-11-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto_url',
            field=models.URLField(blank=True, max_length=700, null=True, verbose_name='URL de foto del candidato'),
        ),
    ]
