# Generated by Django 5.2.7 on 2025-10-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('dni', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('rol', models.CharField(choices=[('votante', 'Votante'), ('invitado', 'Invitado')], default='votante', max_length=10, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.region', verbose_name='Región')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['dni'], name='usuarios_dni_5caf68_idx')],
            },
        ),
    ]
