# Generated by Django 5.2.7 on 2025-10-26 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos_recibidos', to='candidatos.candidato', verbose_name='Candidato')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo', verbose_name='Cargo votado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'votos',
                'indexes': [models.Index(fields=['usuario', 'cargo'], name='votos_usuario_229492_idx'), models.Index(fields=['candidato'], name='votos_candida_fdaa01_idx'), models.Index(fields=['created_at'], name='votos_created_7b7b30_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'cargo'), name='unique_voto_por_cargo')],
            },
        ),
    ]
